#Easemob rest api server domain
API_SERVER_HOST = a1.easemob.com

#Appkey, just for test
APPKEY = 15810799888#5l5cwfj

#App client id of the app above
APP_CLIENT_ID = YXA6J4zA0JcoEeWTzidE6iYg-A

#App client secret of the app above
APP_CLIENT_SECRET = YXA6A4ptp3u-frJTiaTAE5AlhXAMZKU
