# deploy can be set local or remote.
127.0.0.1.ICT.Deploy=local
# if deploy=local,FileLocation is usefull.
127.0.0.1.ICT.FileLocation=D\:\\Program Files\\\u4E2D\u56FD\u519C\u4E1A\u94F6\u884C\\\u4E2D\u56FD\u519C\u4E1A\u94F6\u884C\u94F6\u4F01\u901A\u5E73\u53F0\\detail
# IPAddress can be ignored.
127.0.0.1.ICT.IPAddress=127.0.0.1
127.0.0.1.ICT.Port=21
127.0.0.1.ICT.UserName=zhaofang
127.0.0.1.ICT.Password=zhb@0909
# ftp client's local file directory.
127.0.0.1.ICT.LocalDir=D\:\\yqt\\detail
