template_update_delay=1
datetime_format=yyyy-MM-dd HH\:mm\:ss 
date_format=yyyy-MM-dd 
time_format=HH\:mm\:ss 
number_format=0.\#\#\#\#\#\#; 
boolean_format=true,false 
#auto_import="/WEB-INF/ftl_lib/ponyjava.com/index.ftl" as p, "/WEB-INF/ftl_lib/expoStore/index.ftl" as expo
#whitespace_stripping=true 
default_encoding=UTF-8
#tag_syntax=auto_detect 
url_escaping_charset=UTF-8 
#\u9ED8\u8BA4\u60C5\u51B5\u53D8\u91CF\u4E3Anull\u5219\u66FF\u6362\u4E3A\u7A7A\u5B57\u7B26\u4E32
classic_compatible=true