#MerchantID

chinapay.merid = 808080211302145

#BatchContent FilePath
chinapay.BatchContent.filepath = D:\\daifu\\BatchSerForORA\\

#MerchantKey FilePath
chinapay.merkey.filepath  = D:\\programs\\tomcat7-my\\webapps\\hyplat\\daifu\\batch\\key\\MerPrK.key
#PublicKey FilePath
chinapay.pubkey.filepath = D:\\programs\\tomcat7-my\\webapps\\hyplat\\daifu\\batch\\key\\PgPubk.key

#BatchSer PostURL(Test environment)
#chinapay.oraBatchSer.url = http://131.252.83.215/oraBatchSer/RecFile	
#chinapay.oraBatchSer.url = http://sfj-test.chinapay.com/dac/BatchPayGBK

#BatchSer PostURL(Production environment)
#chinapay.oraBatchSer.url = https://ora.chinapay.com/oraBatchSer/RecFile
chinapay.oraBatchSer.url = http://sfj.chinapay.com/dac/BatchPayGBK

#DownFileSer PostURL(Test environment)
#chinapay.oraDownFileSer.url = http://131.252.83.215/oraDownFileServer/DownFileExe
#chinapay.oraDownFileSer.url = http://sfj-test.chinapay.com/dac/DownFileExe

#DownFileSer PostURL(Production environment)
#chinapay.oraDownFileSer.url = https://ora.chinapay.com/oraDownFileServer/DownFileExe
chinapay.oraDownFileSer.url = http://sfj.chinapay.com/dac/DownFileExe

#Query PostURL(Test environment)
#chinapay.FileStatQuery.url = http://131.252.83.215:9080/filestatquery/fStatQuSer
#chinapay.FileStatQuery.url = http://sfj-test.chinapay.com/dac/FileStatQuSer

#Query PostURL(Production environment)
#chinapay.FileStatQuery.url =https://ora.chinapay.com/filestatquery/fStatQuSer
chinapay.FileStatQuery.url =http://sfj.chinapay.com/dac/FileStatQuSer