#MerchantID
chinapay.merid = 808080211301725

#MerchantKey FilePath
chinapay.merkey.filepath = D\:\\svn-work\\hyplat\\WebRoot\\daifu\\single\\key\\MerPrK.key

#PublicKey FilePath
chinapay.pubkey.filepath = D\:\\svn-work\\hyplat\\WebRoot\\daifu\\single\\key\\PgPubk.key

#Payment PostURL(Test environment)
#chinapay.payment.url = http://sfj-test.chinapay.com/dac/SinPayServletGBK

#Payment PostURL(Production environment)
chinapay.payment.url = http://sfj.chinapay.com/dac/SinPayServletGBK

#Refund PostURL(Test environment)
#chinapay.BatchOrderQuery.url = http://sfj-test.chinapay.com/dac/FailureTradeQueryGBK

#Refund PostURL(Production environment)
chinapay.BatchOrderQuery.url = http\://ora.chinapay.com/oraquery/BatchOrderQuery 

#Query PostURL(Test environment)
#chinapay.query.url = http://sfj-test.chinapay.com/dac/SinPayQueryServletGBK

#Query PostURL(Production environment)
chinapay.query.url = http://sfj.chinapay.com/dac/SinPayQueryServletGBK

#Query PostURL(Test environment)
#chinapay.BalanceQuery.url = http://sfj-test.chinapay.com/dac/BalanceQueryGBK

#Query balance PostURL(Production environment)
chinapay.BalanceQuery.url = http\://sfj.chinapay.com/dac/BalanceQueryGBK

#Query balance detail PostURL(Test environment)
#chinapay.DepositDetailQuery.url = http://sfj-test.chinapay.com/dac/DepositDetailQueryGBK

#Query balance detail PostURL(Production environment)
chinapay.DepositDetailQuery.url =http\://ora.chinapay.com/oraquery/DepositDetailQuery